spring:
  application:
    name: certchain

  datasource:
    url: jdbc:postgresql://localhost:5432/certichain
    username: certichain
    password: certichain_password
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 6969
